### ISSUE TITLE
Compatibility with Python 2.7

### ISSUE THREAD

**Issue by arkraft** [gabrielmagno/nano-dlna#1]
The setup.py specifies that this package is compatible with Python 2.7. When executing `nanodlna list` i get the error `No module named request`. Devices.py imports `urllib.request` which is, as far as i understand a Python 3 package. Is there a possibility to run nanodlna with Python 2.7?

**Comment by gabrielmagno** [comment]
You are right. It looks like easy to fix. I will take a look into it next week. If I don't, please ping me again :-P. Thank you for reporting!

**Comment by arkraft** [comment]
That was a fast one^^. Thank you for this

**Comment by gabrielmagno** [comment]
Last commit, which bumped nanodlna to version 0.1.3, closes this issue. It is now working on Python 2. :-)

**Comment by gabrielmagno** [comment]
It is fixed now. Version 0.1.4 is up and running  :-)
