### ISSUE TITLE
question : compatible with micropython ans esp32 ?

### ISSUE THREAD

**Issue by picpic020960** [gabrielmagno/nano-dlna#10]
hello ,
want dlna for my twatch2020.
  nanodlna run with micropython as python ?
Thanks for info 
Regards

**Comment by gabrielmagno** [comment]
Hello @picpic020960 .

I'm not very familiar with micropython and I don't have a device with it, so unfortunately I will not be able to test it.

But I can tell you that nano-dlna uses pure python code, and has only the "Twisted" Python library as a dependency. So, I believe that if Twisted is compatible with micropython, nano-dlna will also be.
